### ISSUE TITLE
Wrong test cases

### ISSUE THREAD

**Issue by Jack-Works** [Tokimon/es-feature-detection#21]
1. `WeekMap` -> `WeakMap`
https://github.com/Tokimon/es-feature-detection/blob/master/builtins/es2015.json#L14

2. `WeekSet` -> `WeakSet`
https://github.com/Tokimon/es-feature-detection/blob/master/builtins/es2015.json#L15

3. `Number.isFininte` -> `Number.isFinite`
https://github.com/Tokimon/es-feature-detection/blob/master/builtins/es2015.json#L35

4. RegExp.prototype.sticky
https://github.com/Tokimon/es-feature-detection/blob/master/syntax/es2015.json#L4:21
```js
(new RegExp('foo','y')).sticky === true
```

5. RegExp.prototype.unicode
```js
(new RegExp('\u{61}', 'u')).unicode === true
```

**Comment by Tokimon** [comment]
Hey man thanks for the ticket.
I didn't get the notice about the post, so I only just saw your corrections. Amazing!
Thanks for helping out
